# The name of your Worker. Alphanumeric values and dashes only.
name = "comment-worker"

# The entrypoint/path to the file that will be executed.
main = "./src/index.js"

# Whether you use `<NAME>.<SUBDOMAIN>.workers.dev` to
# test and deploy your Worker.
# @default `true`
workers_dev = true

# A date in the form yyyy-mm-dd, which will be used to determine
# which version of the Workers runtime is used.
compatibility_date = "2023-08-11"

## example config ##
#routes = [
#    { pattern = "comments.zanechua.com", custom_domain = true }
#]
#
[vars]
GITHUB_APP_ID = "1109399"
GITHUB_ORGANIZATION_SLUG = "idroulia"
GITHUB_REPOSITORY_SLUG = "Mamazilla-MoodForFood"
GITHUB_REPOSITORY_BRANCH = "main"
CW_ALLOWED_ORIGINS = "https://mamazillafood.com,https://www.mamazillafood.com,http://127.0.0.1:4000"
CW_DEBUG = "false"
GITHUB_APP_PRIVATE_KEY = ""
RECAPTCHA_SECRET_KEY = ""